theme: minima
title: Visualització de dades - UOC
description: PAC de l'assignatura Visualització de dades del Màster de Ciència de Dades de la UOC.

index_layout: home

assets:
  - timeline/timeline.js
